//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.19 at 08:59:05 AM CET 
//


package fasz;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the fasz package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: fasz
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ROOT }
     * 
     */
    public ROOT createROOT() {
        return new ROOT();
    }

    /**
     * Create an instance of {@link ROOT.Authors }
     * 
     */
    public ROOT.Authors createROOTAuthors() {
        return new ROOT.Authors();
    }

    /**
     * Create an instance of {@link ROOT.Publishers }
     * 
     */
    public ROOT.Publishers createROOTPublishers() {
        return new ROOT.Publishers();
    }

    /**
     * Create an instance of {@link ROOT.Books }
     * 
     */
    public ROOT.Books createROOTBooks() {
        return new ROOT.Books();
    }

    /**
     * Create an instance of {@link ROOT.Books.Book }
     * 
     */
    public ROOT.Books.Book createROOTBooksBook() {
        return new ROOT.Books.Book();
    }

    /**
     * Create an instance of {@link ROOT.Books.Book.Copies }
     * 
     */
    public ROOT.Books.Book.Copies createROOTBooksBookCopies() {
        return new ROOT.Books.Book.Copies();
    }

    /**
     * Create an instance of {@link ROOT.Books.Book.Copies.Copy }
     * 
     */
    public ROOT.Books.Book.Copies.Copy createROOTBooksBookCopiesCopy() {
        return new ROOT.Books.Book.Copies.Copy();
    }

    /**
     * Create an instance of {@link ROOT.Borrows }
     * 
     */
    public ROOT.Borrows createROOTBorrows() {
        return new ROOT.Borrows();
    }

    /**
     * Create an instance of {@link ROOT.Readers }
     * 
     */
    public ROOT.Readers createROOTReaders() {
        return new ROOT.Readers();
    }

    /**
     * Create an instance of {@link ROOT.Readers.Reader }
     * 
     */
    public ROOT.Readers.Reader createROOTReadersReader() {
        return new ROOT.Readers.Reader();
    }

    /**
     * Create an instance of {@link ROOT.Bookings }
     * 
     */
    public ROOT.Bookings createROOTBookings() {
        return new ROOT.Bookings();
    }

    /**
     * Create an instance of {@link TypeBooking }
     * 
     */
    public TypeBooking createTypeBooking() {
        return new TypeBooking();
    }

    /**
     * Create an instance of {@link TypeAddress }
     * 
     */
    public TypeAddress createTypeAddress() {
        return new TypeAddress();
    }

    /**
     * Create an instance of {@link ROOT.Authors.Author }
     * 
     */
    public ROOT.Authors.Author createROOTAuthorsAuthor() {
        return new ROOT.Authors.Author();
    }

    /**
     * Create an instance of {@link ROOT.Publishers.Publisher }
     * 
     */
    public ROOT.Publishers.Publisher createROOTPublishersPublisher() {
        return new ROOT.Publishers.Publisher();
    }

    /**
     * Create an instance of {@link ROOT.Books.Book.Copies.Copy.Borrowed }
     * 
     */
    public ROOT.Books.Book.Copies.Copy.Borrowed createROOTBooksBookCopiesCopyBorrowed() {
        return new ROOT.Books.Book.Copies.Copy.Borrowed();
    }

    /**
     * Create an instance of {@link ROOT.Borrows.Borrow }
     * 
     */
    public ROOT.Borrows.Borrow createROOTBorrowsBorrow() {
        return new ROOT.Borrows.Borrow();
    }

    /**
     * Create an instance of {@link ROOT.Readers.Reader.Registered }
     * 
     */
    public ROOT.Readers.Reader.Registered createROOTReadersReaderRegistered() {
        return new ROOT.Readers.Reader.Registered();
    }

    /**
     * Create an instance of {@link ROOT.Readers.Reader.Name }
     * 
     */
    public ROOT.Readers.Reader.Name createROOTReadersReaderName() {
        return new ROOT.Readers.Reader.Name();
    }

    /**
     * Create an instance of {@link ROOT.Readers.Reader.Address }
     * 
     */
    public ROOT.Readers.Reader.Address createROOTReadersReaderAddress() {
        return new ROOT.Readers.Reader.Address();
    }

}
