//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.19 at 08:59:05 AM CET 
//


package fasz;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Readers">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Reader" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="E-mail" type="{}E-mail"/>
 *                             &lt;element name="Telephone" type="{}Telephone" minOccurs="0"/>
 *                             &lt;element name="Occupation" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Date_of_enrollment" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                             &lt;element name="Registered" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="Name">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="First_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="Last_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="Address">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;extension base="{}Type_Address">
 *                                     &lt;sequence>
 *                                       &lt;element name="Street" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *                                       &lt;element name="Number" type="{}StrNo"/>
 *                                     &lt;/sequence>
 *                                   &lt;/extension>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attribute name="ReaderID" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Borrows">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Borrow" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Date_of_borrowing" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="ReaderID" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="AccessionNumber" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Books">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Book" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Title" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Date_of_publishing" type="{}DateShortened"/>
 *                             &lt;element name="Copies">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="Copy" maxOccurs="unbounded" minOccurs="0">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="Price" type="{}Price"/>
 *                                                 &lt;element name="Borrowed" minOccurs="0">
 *                                                   &lt;complexType>
 *                                                     &lt;complexContent>
 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                                       &lt;/restriction>
 *                                                     &lt;/complexContent>
 *                                                   &lt;/complexType>
 *                                                 &lt;/element>
 *                                               &lt;/sequence>
 *                                               &lt;attribute name="AccessionNumber" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attribute name="ISBN" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="Author" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="Publisher" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Bookings">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Booking" type="{}Type_Booking" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Publishers">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Publisher" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Address" type="{}Type_Address"/>
 *                             &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="PublisherID" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Authors">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Author" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="First_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Last_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="AuthorID" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "readers",
    "borrows",
    "books",
    "bookings",
    "publishers",
    "authors"
})
@XmlRootElement(name = "ROOT")
public class ROOT {

    @XmlElement(name = "Readers", required = true)
    protected ROOT.Readers readers;
    @XmlElement(name = "Borrows", required = true)
    protected ROOT.Borrows borrows;
    @XmlElement(name = "Books", required = true)
    protected ROOT.Books books;
    @XmlElement(name = "Bookings", required = true)
    protected ROOT.Bookings bookings;
    @XmlElement(name = "Publishers", required = true)
    protected ROOT.Publishers publishers;
    @XmlElement(name = "Authors", required = true)
    protected ROOT.Authors authors;

    /**
     * Gets the value of the readers property.
     * 
     * @return
     *     possible object is
     *     {@link ROOT.Readers }
     *     
     */
    public ROOT.Readers getReaders() {
        return readers;
    }

    /**
     * Sets the value of the readers property.
     * 
     * @param value
     *     allowed object is
     *     {@link ROOT.Readers }
     *     
     */
    public void setReaders(ROOT.Readers value) {
        this.readers = value;
    }

    /**
     * Gets the value of the borrows property.
     * 
     * @return
     *     possible object is
     *     {@link ROOT.Borrows }
     *     
     */
    public ROOT.Borrows getBorrows() {
        return borrows;
    }

    /**
     * Sets the value of the borrows property.
     * 
     * @param value
     *     allowed object is
     *     {@link ROOT.Borrows }
     *     
     */
    public void setBorrows(ROOT.Borrows value) {
        this.borrows = value;
    }

    /**
     * Gets the value of the books property.
     * 
     * @return
     *     possible object is
     *     {@link ROOT.Books }
     *     
     */
    public ROOT.Books getBooks() {
        return books;
    }

    /**
     * Sets the value of the books property.
     * 
     * @param value
     *     allowed object is
     *     {@link ROOT.Books }
     *     
     */
    public void setBooks(ROOT.Books value) {
        this.books = value;
    }

    /**
     * Gets the value of the bookings property.
     * 
     * @return
     *     possible object is
     *     {@link ROOT.Bookings }
     *     
     */
    public ROOT.Bookings getBookings() {
        return bookings;
    }

    /**
     * Sets the value of the bookings property.
     * 
     * @param value
     *     allowed object is
     *     {@link ROOT.Bookings }
     *     
     */
    public void setBookings(ROOT.Bookings value) {
        this.bookings = value;
    }

    /**
     * Gets the value of the publishers property.
     * 
     * @return
     *     possible object is
     *     {@link ROOT.Publishers }
     *     
     */
    public ROOT.Publishers getPublishers() {
        return publishers;
    }

    /**
     * Sets the value of the publishers property.
     * 
     * @param value
     *     allowed object is
     *     {@link ROOT.Publishers }
     *     
     */
    public void setPublishers(ROOT.Publishers value) {
        this.publishers = value;
    }

    /**
     * Gets the value of the authors property.
     * 
     * @return
     *     possible object is
     *     {@link ROOT.Authors }
     *     
     */
    public ROOT.Authors getAuthors() {
        return authors;
    }

    /**
     * Sets the value of the authors property.
     * 
     * @param value
     *     allowed object is
     *     {@link ROOT.Authors }
     *     
     */
    public void setAuthors(ROOT.Authors value) {
        this.authors = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Author" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="First_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Last_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="AuthorID" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "author"
    })
    public static class Authors {

        @XmlElement(name = "Author")
        protected List<ROOT.Authors.Author> author;

        /**
         * Gets the value of the author property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the author property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAuthor().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ROOT.Authors.Author }
         * 
         * 
         */
        public List<ROOT.Authors.Author> getAuthor() {
            if (author == null) {
                author = new ArrayList<ROOT.Authors.Author>();
            }
            return this.author;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="First_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Last_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *       &lt;attribute name="AuthorID" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "firstName",
            "lastName"
        })
        public static class Author {

            @XmlElement(name = "First_name", required = true)
            protected String firstName;
            @XmlElement(name = "Last_name", required = true)
            protected String lastName;
            @XmlAttribute(name = "AuthorID", required = true)
            protected String authorID;

            /**
             * Gets the value of the firstName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFirstName() {
                return firstName;
            }

            /**
             * Sets the value of the firstName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFirstName(String value) {
                this.firstName = value;
            }

            /**
             * Gets the value of the lastName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getLastName() {
                return lastName;
            }

            /**
             * Sets the value of the lastName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setLastName(String value) {
                this.lastName = value;
            }

            /**
             * Gets the value of the authorID property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAuthorID() {
                return authorID;
            }

            /**
             * Sets the value of the authorID property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAuthorID(String value) {
                this.authorID = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Booking" type="{}Type_Booking" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "booking"
    })
    public static class Bookings {

        @XmlElement(name = "Booking")
        protected List<TypeBooking> booking;

        /**
         * Gets the value of the booking property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the booking property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getBooking().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TypeBooking }
         * 
         * 
         */
        public List<TypeBooking> getBooking() {
            if (booking == null) {
                booking = new ArrayList<TypeBooking>();
            }
            return this.booking;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Book" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Title" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Date_of_publishing" type="{}DateShortened"/>
     *                   &lt;element name="Copies">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="Copy" maxOccurs="unbounded" minOccurs="0">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="Price" type="{}Price"/>
     *                                       &lt;element name="Borrowed" minOccurs="0">
     *                                         &lt;complexType>
     *                                           &lt;complexContent>
     *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                             &lt;/restriction>
     *                                           &lt;/complexContent>
     *                                         &lt;/complexType>
     *                                       &lt;/element>
     *                                     &lt;/sequence>
     *                                     &lt;attribute name="AccessionNumber" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *                 &lt;attribute name="ISBN" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="Author" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="Publisher" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "book"
    })
    public static class Books {

        @XmlElement(name = "Book")
        protected List<ROOT.Books.Book> book;

        /**
         * Gets the value of the book property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the book property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getBook().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ROOT.Books.Book }
         * 
         * 
         */
        public List<ROOT.Books.Book> getBook() {
            if (book == null) {
                book = new ArrayList<ROOT.Books.Book>();
            }
            return this.book;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Title" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Date_of_publishing" type="{}DateShortened"/>
         *         &lt;element name="Copies">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="Copy" maxOccurs="unbounded" minOccurs="0">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="Price" type="{}Price"/>
         *                             &lt;element name="Borrowed" minOccurs="0">
         *                               &lt;complexType>
         *                                 &lt;complexContent>
         *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                                   &lt;/restriction>
         *                                 &lt;/complexContent>
         *                               &lt;/complexType>
         *                             &lt;/element>
         *                           &lt;/sequence>
         *                           &lt;attribute name="AccessionNumber" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *       &lt;attribute name="ISBN" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="Author" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="Publisher" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "title",
            "dateOfPublishing",
            "copies"
        })
        public static class Book {

            @XmlElement(name = "Title", required = true)
            protected String title;
            @XmlElement(name = "Date_of_publishing", required = true)
            protected String dateOfPublishing;
            @XmlElement(name = "Copies", required = true)
            protected ROOT.Books.Book.Copies copies;
            @XmlAttribute(name = "ISBN", required = true)
            protected String isbn;
            @XmlAttribute(name = "Author", required = true)
            protected String author;
            @XmlAttribute(name = "Publisher", required = true)
            protected String publisher;

            /**
             * Gets the value of the title property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTitle() {
                return title;
            }

            /**
             * Sets the value of the title property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTitle(String value) {
                this.title = value;
            }

            /**
             * Gets the value of the dateOfPublishing property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDateOfPublishing() {
                return dateOfPublishing;
            }

            /**
             * Sets the value of the dateOfPublishing property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDateOfPublishing(String value) {
                this.dateOfPublishing = value;
            }

            /**
             * Gets the value of the copies property.
             * 
             * @return
             *     possible object is
             *     {@link ROOT.Books.Book.Copies }
             *     
             */
            public ROOT.Books.Book.Copies getCopies() {
                return copies;
            }

            /**
             * Sets the value of the copies property.
             * 
             * @param value
             *     allowed object is
             *     {@link ROOT.Books.Book.Copies }
             *     
             */
            public void setCopies(ROOT.Books.Book.Copies value) {
                this.copies = value;
            }

            /**
             * Gets the value of the isbn property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getISBN() {
                return isbn;
            }

            /**
             * Sets the value of the isbn property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setISBN(String value) {
                this.isbn = value;
            }

            /**
             * Gets the value of the author property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAuthor() {
                return author;
            }

            /**
             * Sets the value of the author property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAuthor(String value) {
                this.author = value;
            }

            /**
             * Gets the value of the publisher property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPublisher() {
                return publisher;
            }

            /**
             * Sets the value of the publisher property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPublisher(String value) {
                this.publisher = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="Copy" maxOccurs="unbounded" minOccurs="0">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="Price" type="{}Price"/>
             *                   &lt;element name="Borrowed" minOccurs="0">
             *                     &lt;complexType>
             *                       &lt;complexContent>
             *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                         &lt;/restriction>
             *                       &lt;/complexContent>
             *                     &lt;/complexType>
             *                   &lt;/element>
             *                 &lt;/sequence>
             *                 &lt;attribute name="AccessionNumber" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "copy"
            })
            public static class Copies {

                @XmlElement(name = "Copy")
                protected List<ROOT.Books.Book.Copies.Copy> copy;

                /**
                 * Gets the value of the copy property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the copy property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getCopy().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link ROOT.Books.Book.Copies.Copy }
                 * 
                 * 
                 */
                public List<ROOT.Books.Book.Copies.Copy> getCopy() {
                    if (copy == null) {
                        copy = new ArrayList<ROOT.Books.Book.Copies.Copy>();
                    }
                    return this.copy;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="Price" type="{}Price"/>
                 *         &lt;element name="Borrowed" minOccurs="0">
                 *           &lt;complexType>
                 *             &lt;complexContent>
                 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *               &lt;/restriction>
                 *             &lt;/complexContent>
                 *           &lt;/complexType>
                 *         &lt;/element>
                 *       &lt;/sequence>
                 *       &lt;attribute name="AccessionNumber" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "price",
                    "borrowed"
                })
                public static class Copy {

                    @XmlElement(name = "Price", required = true)
                    protected BigInteger price;
                    @XmlElement(name = "Borrowed")
                    protected ROOT.Books.Book.Copies.Copy.Borrowed borrowed;
                    @XmlAttribute(name = "AccessionNumber", required = true)
                    protected String accessionNumber;

                    /**
                     * Gets the value of the price property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link BigInteger }
                     *     
                     */
                    public BigInteger getPrice() {
                        return price;
                    }

                    /**
                     * Sets the value of the price property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link BigInteger }
                     *     
                     */
                    public void setPrice(BigInteger value) {
                        this.price = value;
                    }

                    /**
                     * Gets the value of the borrowed property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link ROOT.Books.Book.Copies.Copy.Borrowed }
                     *     
                     */
                    public ROOT.Books.Book.Copies.Copy.Borrowed getBorrowed() {
                        return borrowed;
                    }

                    /**
                     * Sets the value of the borrowed property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link ROOT.Books.Book.Copies.Copy.Borrowed }
                     *     
                     */
                    public void setBorrowed(ROOT.Books.Book.Copies.Copy.Borrowed value) {
                        this.borrowed = value;
                    }

                    /**
                     * Gets the value of the accessionNumber property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getAccessionNumber() {
                        return accessionNumber;
                    }

                    /**
                     * Sets the value of the accessionNumber property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setAccessionNumber(String value) {
                        this.accessionNumber = value;
                    }


                    /**
                     * <p>Java class for anonymous complex type.
                     * 
                     * <p>The following schema fragment specifies the expected content contained within this class.
                     * 
                     * <pre>
                     * &lt;complexType>
                     *   &lt;complexContent>
                     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                     *     &lt;/restriction>
                     *   &lt;/complexContent>
                     * &lt;/complexType>
                     * </pre>
                     * 
                     * 
                     */
                    @XmlAccessorType(XmlAccessType.FIELD)
                    @XmlType(name = "")
                    public static class Borrowed {


                    }

                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Borrow" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Date_of_borrowing" type="{http://www.w3.org/2001/XMLSchema}date"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="ReaderID" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="AccessionNumber" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "borrow"
    })
    public static class Borrows {

        @XmlElement(name = "Borrow")
        protected List<ROOT.Borrows.Borrow> borrow;

        /**
         * Gets the value of the borrow property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the borrow property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getBorrow().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ROOT.Borrows.Borrow }
         * 
         * 
         */
        public List<ROOT.Borrows.Borrow> getBorrow() {
            if (borrow == null) {
                borrow = new ArrayList<ROOT.Borrows.Borrow>();
            }
            return this.borrow;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Date_of_borrowing" type="{http://www.w3.org/2001/XMLSchema}date"/>
         *       &lt;/sequence>
         *       &lt;attribute name="ReaderID" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="AccessionNumber" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "dateOfBorrowing"
        })
        public static class Borrow {

            @XmlElement(name = "Date_of_borrowing", required = true)
            @XmlSchemaType(name = "date")
            protected XMLGregorianCalendar dateOfBorrowing;
            @XmlAttribute(name = "ReaderID", required = true)
            protected String readerID;
            @XmlAttribute(name = "AccessionNumber", required = true)
            protected String accessionNumber;

            /**
             * Gets the value of the dateOfBorrowing property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getDateOfBorrowing() {
                return dateOfBorrowing;
            }

            /**
             * Sets the value of the dateOfBorrowing property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setDateOfBorrowing(XMLGregorianCalendar value) {
                this.dateOfBorrowing = value;
            }

            /**
             * Gets the value of the readerID property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getReaderID() {
                return readerID;
            }

            /**
             * Sets the value of the readerID property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setReaderID(String value) {
                this.readerID = value;
            }

            /**
             * Gets the value of the accessionNumber property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAccessionNumber() {
                return accessionNumber;
            }

            /**
             * Sets the value of the accessionNumber property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAccessionNumber(String value) {
                this.accessionNumber = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Publisher" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Address" type="{}Type_Address"/>
     *                   &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="PublisherID" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "publisher"
    })
    public static class Publishers {

        @XmlElement(name = "Publisher")
        protected List<ROOT.Publishers.Publisher> publisher;

        /**
         * Gets the value of the publisher property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the publisher property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPublisher().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ROOT.Publishers.Publisher }
         * 
         * 
         */
        public List<ROOT.Publishers.Publisher> getPublisher() {
            if (publisher == null) {
                publisher = new ArrayList<ROOT.Publishers.Publisher>();
            }
            return this.publisher;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Address" type="{}Type_Address"/>
         *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *       &lt;attribute name="PublisherID" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "address",
            "name"
        })
        public static class Publisher {

            @XmlElement(name = "Address", required = true)
            protected TypeAddress address;
            @XmlElement(name = "Name", required = true)
            protected String name;
            @XmlAttribute(name = "PublisherID", required = true)
            protected String publisherID;

            /**
             * Gets the value of the address property.
             * 
             * @return
             *     possible object is
             *     {@link TypeAddress }
             *     
             */
            public TypeAddress getAddress() {
                return address;
            }

            /**
             * Sets the value of the address property.
             * 
             * @param value
             *     allowed object is
             *     {@link TypeAddress }
             *     
             */
            public void setAddress(TypeAddress value) {
                this.address = value;
            }

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the publisherID property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPublisherID() {
                return publisherID;
            }

            /**
             * Sets the value of the publisherID property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPublisherID(String value) {
                this.publisherID = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Reader" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="E-mail" type="{}E-mail"/>
     *                   &lt;element name="Telephone" type="{}Telephone" minOccurs="0"/>
     *                   &lt;element name="Occupation" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Date_of_enrollment" type="{http://www.w3.org/2001/XMLSchema}date"/>
     *                   &lt;element name="Registered" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="Name">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="First_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="Last_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="Address">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;extension base="{}Type_Address">
     *                           &lt;sequence>
     *                             &lt;element name="Street" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
     *                             &lt;element name="Number" type="{}StrNo"/>
     *                           &lt;/sequence>
     *                         &lt;/extension>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *                 &lt;attribute name="ReaderID" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "reader"
    })
    public static class Readers {

        @XmlElement(name = "Reader")
        protected List<ROOT.Readers.Reader> reader;

        /**
         * Gets the value of the reader property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the reader property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getReader().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ROOT.Readers.Reader }
         * 
         * 
         */
        public List<ROOT.Readers.Reader> getReader() {
            if (reader == null) {
                reader = new ArrayList<ROOT.Readers.Reader>();
            }
            return this.reader;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="E-mail" type="{}E-mail"/>
         *         &lt;element name="Telephone" type="{}Telephone" minOccurs="0"/>
         *         &lt;element name="Occupation" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Date_of_enrollment" type="{http://www.w3.org/2001/XMLSchema}date"/>
         *         &lt;element name="Registered" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="Name">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="First_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="Last_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="Address">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;extension base="{}Type_Address">
         *                 &lt;sequence>
         *                   &lt;element name="Street" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
         *                   &lt;element name="Number" type="{}StrNo"/>
         *                 &lt;/sequence>
         *               &lt;/extension>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *       &lt;attribute name="ReaderID" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "eMail",
            "telephone",
            "occupation",
            "dateOfEnrollment",
            "registered",
            "name",
            "address"
        })
        public static class Reader {

            @XmlElement(name = "E-mail", required = true)
            protected String eMail;
            @XmlElement(name = "Telephone")
            protected String telephone;
            @XmlElement(name = "Occupation", required = true)
            protected String occupation;
            @XmlElement(name = "Date_of_enrollment", required = true)
            @XmlSchemaType(name = "date")
            protected XMLGregorianCalendar dateOfEnrollment;
            @XmlElement(name = "Registered")
            protected ROOT.Readers.Reader.Registered registered;
            @XmlElement(name = "Name", required = true)
            protected ROOT.Readers.Reader.Name name;
            @XmlElement(name = "Address", required = true)
            protected ROOT.Readers.Reader.Address address;
            @XmlAttribute(name = "ReaderID", required = true)
            protected String readerID;

            /**
             * Gets the value of the eMail property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEMail() {
                return eMail;
            }

            /**
             * Sets the value of the eMail property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEMail(String value) {
                this.eMail = value;
            }

            /**
             * Gets the value of the telephone property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTelephone() {
                return telephone;
            }

            /**
             * Sets the value of the telephone property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTelephone(String value) {
                this.telephone = value;
            }

            /**
             * Gets the value of the occupation property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getOccupation() {
                return occupation;
            }

            /**
             * Sets the value of the occupation property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setOccupation(String value) {
                this.occupation = value;
            }

            /**
             * Gets the value of the dateOfEnrollment property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getDateOfEnrollment() {
                return dateOfEnrollment;
            }

            /**
             * Sets the value of the dateOfEnrollment property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setDateOfEnrollment(XMLGregorianCalendar value) {
                this.dateOfEnrollment = value;
            }

            /**
             * Gets the value of the registered property.
             * 
             * @return
             *     possible object is
             *     {@link ROOT.Readers.Reader.Registered }
             *     
             */
            public ROOT.Readers.Reader.Registered getRegistered() {
                return registered;
            }

            /**
             * Sets the value of the registered property.
             * 
             * @param value
             *     allowed object is
             *     {@link ROOT.Readers.Reader.Registered }
             *     
             */
            public void setRegistered(ROOT.Readers.Reader.Registered value) {
                this.registered = value;
            }

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link ROOT.Readers.Reader.Name }
             *     
             */
            public ROOT.Readers.Reader.Name getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link ROOT.Readers.Reader.Name }
             *     
             */
            public void setName(ROOT.Readers.Reader.Name value) {
                this.name = value;
            }

            /**
             * Gets the value of the address property.
             * 
             * @return
             *     possible object is
             *     {@link ROOT.Readers.Reader.Address }
             *     
             */
            public ROOT.Readers.Reader.Address getAddress() {
                return address;
            }

            /**
             * Sets the value of the address property.
             * 
             * @param value
             *     allowed object is
             *     {@link ROOT.Readers.Reader.Address }
             *     
             */
            public void setAddress(ROOT.Readers.Reader.Address value) {
                this.address = value;
            }

            /**
             * Gets the value of the readerID property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getReaderID() {
                return readerID;
            }

            /**
             * Sets the value of the readerID property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setReaderID(String value) {
                this.readerID = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;extension base="{}Type_Address">
             *       &lt;sequence>
             *         &lt;element name="Street" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
             *         &lt;element name="Number" type="{}StrNo"/>
             *       &lt;/sequence>
             *     &lt;/extension>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "street",
                "number"
            })
            public static class Address
                extends TypeAddress
            {

                @XmlElement(name = "Street")
                protected Object street;
                @XmlElement(name = "Number", required = true)
                protected BigInteger number;

                /**
                 * Gets the value of the street property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Object }
                 *     
                 */
                public Object getStreet() {
                    return street;
                }

                /**
                 * Sets the value of the street property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Object }
                 *     
                 */
                public void setStreet(Object value) {
                    this.street = value;
                }

                /**
                 * Gets the value of the number property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link BigInteger }
                 *     
                 */
                public BigInteger getNumber() {
                    return number;
                }

                /**
                 * Sets the value of the number property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link BigInteger }
                 *     
                 */
                public void setNumber(BigInteger value) {
                    this.number = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="First_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="Last_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "firstName",
                "lastName"
            })
            public static class Name {

                @XmlElement(name = "First_name", required = true)
                protected String firstName;
                @XmlElement(name = "Last_name", required = true)
                protected String lastName;

                /**
                 * Gets the value of the firstName property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getFirstName() {
                    return firstName;
                }

                /**
                 * Sets the value of the firstName property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setFirstName(String value) {
                    this.firstName = value;
                }

                /**
                 * Gets the value of the lastName property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getLastName() {
                    return lastName;
                }

                /**
                 * Sets the value of the lastName property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setLastName(String value) {
                    this.lastName = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class Registered {


            }

        }

    }

}
